version: '3'

services:
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: ./dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/microservices-439614/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    depends_on:
      - nats-server

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: ./dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/microservices-439614/image-registry/auth-ms
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - nats-server
      - client-gateway

  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  products-ms:
    build:
      context: products-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/microservices-439614/image-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db
    depends_on:
      - nats-server
      - client-gateway

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: ./dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/microservices-439614/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
    depends_on:
      - nats-server
      - client-gateway

  orders-ms:
    build:
      context: orders-ms
      dockerfile: ./dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: europe-southwest1-docker.pkg.dev/microservices-439614/image-registry/orders-ms
    environment:
      - PORT=3002
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
